/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type LandingPageOverridesProps = {
    LandingPage?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 68"?: PrimitiveOverrideProps<ViewProps>;
    logo21684?: PrimitiveOverrideProps<ViewProps>;
    bottle21697?: PrimitiveOverrideProps<IconProps>;
    "Valkyrie Landing Page"?: PrimitiveOverrideProps<TextProps>;
    "Vector 33"?: PrimitiveOverrideProps<IconProps>;
    "Vector 34"?: PrimitiveOverrideProps<IconProps>;
    "Order Status"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 63"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 41"?: PrimitiveOverrideProps<ViewProps>;
    Vector218506?: PrimitiveOverrideProps<IconProps>;
    VALKYRIE?: PrimitiveOverrideProps<TextProps>;
    logo218508?: PrimitiveOverrideProps<ViewProps>;
    wing218509?: PrimitiveOverrideProps<ViewProps>;
    Vector218510?: PrimitiveOverrideProps<IconProps>;
    Vector218511?: PrimitiveOverrideProps<IconProps>;
    Vector218512?: PrimitiveOverrideProps<IconProps>;
    Vector218513?: PrimitiveOverrideProps<IconProps>;
    Vector218514?: PrimitiveOverrideProps<IconProps>;
    Vector218515?: PrimitiveOverrideProps<IconProps>;
    Vector218516?: PrimitiveOverrideProps<IconProps>;
    Vector218517?: PrimitiveOverrideProps<IconProps>;
    Vector218518?: PrimitiveOverrideProps<IconProps>;
    Vector218519?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 40218520"?: PrimitiveOverrideProps<ViewProps>;
    bottle218521?: PrimitiveOverrideProps<IconProps>;
    "Group 2"?: PrimitiveOverrideProps<ViewProps>;
    wing218523?: PrimitiveOverrideProps<ViewProps>;
    Vector218524?: PrimitiveOverrideProps<IconProps>;
    Vector218525?: PrimitiveOverrideProps<IconProps>;
    Vector218526?: PrimitiveOverrideProps<IconProps>;
    Vector218527?: PrimitiveOverrideProps<IconProps>;
    Vector218528?: PrimitiveOverrideProps<IconProps>;
    Vector218529?: PrimitiveOverrideProps<IconProps>;
    Vector218530?: PrimitiveOverrideProps<IconProps>;
    Vector218531?: PrimitiveOverrideProps<IconProps>;
    Vector218532?: PrimitiveOverrideProps<IconProps>;
    Vector218533?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 40218534"?: PrimitiveOverrideProps<ViewProps>;
    Group218535?: PrimitiveOverrideProps<ViewProps>;
    Vector218536?: PrimitiveOverrideProps<IconProps>;
    "bi:battery-full"?: PrimitiveOverrideProps<ViewProps>;
    Group218538?: PrimitiveOverrideProps<ViewProps>;
    Vector218539?: PrimitiveOverrideProps<IconProps>;
    Vector218540?: PrimitiveOverrideProps<IconProps>;
    wifi?: PrimitiveOverrideProps<ViewProps>;
    Vector218542?: PrimitiveOverrideProps<IconProps>;
    "10:30"?: PrimitiveOverrideProps<TextProps>;
    "mdi:message"?: PrimitiveOverrideProps<ViewProps>;
    Vector218545?: PrimitiveOverrideProps<IconProps>;
    Messages?: PrimitiveOverrideProps<TextProps>;
    Settings?: PrimitiveOverrideProps<TextProps>;
    "material-symbols:settings"?: PrimitiveOverrideProps<ViewProps>;
    Vector218549?: PrimitiveOverrideProps<IconProps>;
    "Where\u2019s My Order?"?: PrimitiveOverrideProps<TextProps>;
    Vector218551?: PrimitiveOverrideProps<IconProps>;
    Cart?: PrimitiveOverrideProps<TextProps>;
    "Bottom Nav Bar"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 46"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 38"?: PrimitiveOverrideProps<ViewProps>;
    Vector218556?: PrimitiveOverrideProps<IconProps>;
    Vector218557?: PrimitiveOverrideProps<IconProps>;
    home?: PrimitiveOverrideProps<ViewProps>;
    Vector218559?: PrimitiveOverrideProps<IconProps>;
    "Vector 1"?: PrimitiveOverrideProps<IconProps>;
    Home?: PrimitiveOverrideProps<TextProps>;
    Browse?: PrimitiveOverrideProps<TextProps>;
    Account?: PrimitiveOverrideProps<TextProps>;
    "Navigtation bar218564"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1218565"?: PrimitiveOverrideProps<IconProps>;
    Vector218566?: PrimitiveOverrideProps<IconProps>;
    Vector218567?: PrimitiveOverrideProps<IconProps>;
    "il:market218568"?: PrimitiveOverrideProps<ViewProps>;
    Vector218569?: PrimitiveOverrideProps<IconProps>;
    Group218570?: PrimitiveOverrideProps<ViewProps>;
    Vector218571?: PrimitiveOverrideProps<IconProps>;
    Vector218572?: PrimitiveOverrideProps<IconProps>;
    "Line 2218573"?: PrimitiveOverrideProps<IconProps>;
    "Navigtation bar218574"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1218575"?: PrimitiveOverrideProps<IconProps>;
    Vector218576?: PrimitiveOverrideProps<IconProps>;
    Vector218577?: PrimitiveOverrideProps<IconProps>;
    "il:market218578"?: PrimitiveOverrideProps<ViewProps>;
    Vector218579?: PrimitiveOverrideProps<IconProps>;
    Group218580?: PrimitiveOverrideProps<ViewProps>;
    Vector218581?: PrimitiveOverrideProps<IconProps>;
    Vector218582?: PrimitiveOverrideProps<IconProps>;
    "Line 2218583"?: PrimitiveOverrideProps<IconProps>;
    "Order Placed"?: PrimitiveOverrideProps<TextProps>;
    "Order Verified"?: PrimitiveOverrideProps<TextProps>;
    "Order Shipped"?: PrimitiveOverrideProps<TextProps>;
    "Delivered!"?: PrimitiveOverrideProps<TextProps>;
    AppleMap?: PrimitiveOverrideProps<ImageProps>;
    "ORDER #NB10992"?: PrimitiveOverrideProps<TextProps>;
    Vector218590?: PrimitiveOverrideProps<IconProps>;
    Vector218591?: PrimitiveOverrideProps<IconProps>;
    Drone218592?: PrimitiveOverrideProps<ViewProps>;
    Vector218593?: PrimitiveOverrideProps<IconProps>;
    Vector218594?: PrimitiveOverrideProps<IconProps>;
    Drone218595?: PrimitiveOverrideProps<ViewProps>;
    Vector218596?: PrimitiveOverrideProps<IconProps>;
    Vector218597?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 65"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 1"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 2"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 3"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 4"?: PrimitiveOverrideProps<IconProps>;
    Vector218603?: PrimitiveOverrideProps<IconProps>;
    "material-symbols:verified-user-rounded"?: PrimitiveOverrideProps<ViewProps>;
    Vector218605?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 64"?: PrimitiveOverrideProps<ViewProps>;
    Vector218607?: PrimitiveOverrideProps<IconProps>;
    Vector218608?: PrimitiveOverrideProps<IconProps>;
    Vector218609?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type LandingPageProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: LandingPageOverridesProps | undefined | null;
}>;
export default function LandingPage(props: LandingPageProps): React.ReactElement;
